### ISSUE TITLE
device '*' not found

### ISSUE THREAD

**Issue by shadeimi** [askervin/fmbt-androidtest#3]
i got this error running the example using a nexus s emulator with android 4.4.2:

shadeimi@artemisia:~/Software/git/fmbt-androidtest$  fmbt -l test.log regressiontest.conf
Error at adapter_init(): FMBTAndroidRunError: Unexpected exit status 255 from command "['timeout', '-k', '1', '60', 'adb', '-s', '*', 'shell', 'getprop', 'ro.build.version.release']".
    Output: 
    Error: error: device '*' not found

Traceback (most recent call last):
  File "/tmp/remote_pyaal.WGlEMO.py", line 405, in adapter_init
    ret = x()
  File "phone.aal", line 48, in adapter_init1
    d = fmbtandroid.Device()
  File "/usr/local/lib/python2.7/dist-packages/fmbtandroid.py", line 462, in __init__
    deviceName, monkeyOptions=self._monkeyOptions, **adbPortArgs))
  File "/usr/local/lib/python2.7/dist-packages/fmbtandroid.py", line 2231, in __init__
    self._detectFeatures()
  File "/usr/local/lib/python2.7/dist-packages/fmbtandroid.py", line 2325, in _detectFeatures
    timeout=_SHORT_TIMEOUT)[1].splitlines()
  File "/usr/local/lib/python2.7/dist-packages/fmbtandroid.py", line 2286, in _runAdb
    return _run(command, expectedExitStatus=expect, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/fmbtandroid.py", line 265, in _run
    raise FMBTAndroidRunError(msg)

fmbt: regressiontest.conf: 2 Initialising adapter failed:

any ideas?

**Comment by askervin** [comment]
It seems autodetecting the emulator has failed or Python code tries connecting it using an empty string as a serial number. What adb prints to you when you run:
`adb devices`

You should see your device (or Android emulator) in the list. If it's there, please try copy-pasting exact output of the command so I can debug it in more detail. If it's not there, you might need to restart the emulator and check that you can login to it with `adb shell`.

**Comment by shadeimi** [comment]
12:45 $ adb devices
List of devices attached
emulator-5554	device

✔ ~/bin 
12:46 $ env
XDG_VTNR=2
XDG_SESSION_ID=1
VIRTUALENVWRAPPER_SCRIPT=/usr/bin/virtualenvwrapper.sh
HOSTNAME=agathis
ANDROID_HOME=/home/shadeimi/Android/Sdk
SHELL=/bin/bash
TERM=xterm-256color
VTE_VERSION=4203
XDG_MENU_PREFIX=gnome-
HISTSIZE=1000
GJS_DEBUG_OUTPUT=stderr
WINDOWID=39845894
QTDIR=/usr/lib64/qt-3.3
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
QTINC=/usr/lib64/qt-3.3/include
QT_GRAPHICSSYSTEM_CHECKED=1
USER=shadeimi
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
WX_CONFIG=/opt/wx/2.8/bin/wx-config
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/2705,unix/unix:/tmp/.ICE-unix/2705
USERNAME=shadeimi
MAIL=/var/spool/mail/shadeimi
DESKTOP_SESSION=gnome
PATH=/home/shadeimi/Software/node-v0.12.4-linux-x64/bin:/home/shadeimi/Software/node-v0.12.4-linux-x64/lib/node_modules:/home/shadeimi/bin:/home/shadeimi/Software/node-v0.12.4-linux-x64/bin:/home/shadeimi/Software/node-v0.12.4-linux-x64/lib/node_modules:/home/shadeimi/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/shadeimi/Android/Sdk/tools:/home/shadeimi/Android/Sdk/platform-tools:/home/shadeimi/Android/Ndk:/opt/wx/2.8/bin:/home/shadeimi/.local/bin:/home/shadeimi/bin:/home/shadeimi/Android/Sdk/tools:/home/shadeimi/Android/Sdk/platform-tools:/home/shadeimi/Android/Ndk:/opt/wx/2.8/bin
QT_IM_MODULE=ibus
XDG_SESSION_TYPE=x11
PWD=/home/shadeimi/bin
XMODIFIERS=@im=ibus
JAVA_HOME=/usr/java/latest
LANG=it_IT.UTF-8
GDM_LANG=it_IT.UTF-8
MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
KDEDIRS=/usr
LOADEDMODULES=
GDMSESSION=gnome
HISTCONTROL=ignoredups
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
HOME=/home/shadeimi
XDG_SEAT=seat0
SHLVL=2
_VIRTUALENVWRAPPER_API= mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
XDG_SESSION_DESKTOP=gnome
LOGNAME=shadeimi
PYTHONPATH=:/usr/local/lib/python2.7/site-packages:/usr/local/lib64/python2.7/site-packages:/usr/local/lib/python2.7/site-packages:/usr/local/lib64/python2.7/site-packages
QTLIB=/usr/lib64/qt-3.3/lib
CVS_RSH=ssh
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-8GBjkIjQGb,guid=ef3d4f47463c22ae463131b756cd6cb4
MODULESHOME=/usr/share/Modules
LESSOPEN=|/usr/bin/lesspipe.sh %s
WINDOWPATH=2
ANDROID_NDK_HOME=/home/shadeimi/Android/Ndk
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
XDG_CURRENT_DESKTOP=GNOME
XAUTHORITY=/run/user/1000/gdm/Xauthority
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
BASH_FUNC_scl()=() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
_=/usr/bin/env
✔ ~/bin 
12:46 $

**Comment by shadeimi** [comment]
Also:
✘-4 ~/git/fmbt-androidtest [master|✚ 1…10] 
12:51 $ python -c 'import fmbtandroid; fmbtandroid.Device().refreshScreenshot().save("/tmp/screenshot.png")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python2.7/site-packages/fmbtandroid.py", line 469, in __init__
    ", ".join(potentialDevices)))
fmbtandroid.AndroidConnectionError: Could not connect to device(s): emulator-5554.

**Comment by shadeimi** [comment]
This is the output from fmbt-scripter using a real device:

not selecting bitmaps automatically when recording
>>> 
exec: import fmbtandroid
time: 0.000 s
>>> 
exec: sut = fmbtandroid.Device()
exception: Could not connect to device(s): 3134D59F84D100EC.
  Traceback (most recent call last):    
  File "/usr/local/bin/fmbt-scripter", line 1908, in _fmbtExec    
    exec statement in self._fmbtEnv    
  File "<string>", line 1, in <module>    
  File "/usr/local/lib64/python2.7/site-packages/fmbtandroid.py", line 469, in __init__    
    ", ".join(potentialDevices)))    
AndroidConnectionError: Could not connect to device(s): 3134D59F84D100EC.
>>> 
time: 12.875 s
>>> 

✔ ~/git/fmbt-androidtest [master|✚ 1…10] 
13:01 $ adb shell
shell@crespo:/ $ 
130|shell@crespo:/ $ ^D
✔ ~/git/fmbt-androidtest [master|✚ 1…10] 
13:01 $ adb devices
List of devices attached
3134D59F84D100EC	device

✔ ~/git/fmbt-androidtest [master|✚ 1…10] 
13:02 $

**Comment by askervin** [comment]
I've tried to reproduce the problem with adb 1.0.32. Upgraded it to the latest revision (09a0d98bebce-android), but everything seems to work smoothly. I'm running Android 4.4.2 in an emulator and Intel x86 Atom System Image rev. 3., setup is running on a native Linux host (no VMs).

I would suggest running `adb kill-server` and then `adb devices`. It will kill existing adb daemon, thus flushing all port forwards that fmbtandroid has needed, and restart new one. But still I don't believe it's the problem. Please let me know which 4.4.2 image you are using in your emulator and which adb version (and revision) you are running.

**Comment by shadeimi** [comment]
I'm using the same configuration:
15:19 $ adb -v 
Android Debug Bridge version 1.0.32
Revision 09a0d98bebce-android

Nexus-S android 4.4.2 using Intel x86 Atom System Image rev. 3., on Fedora 23

also killing & restarting adb doesn't solve the problem. 
Anyway, this is strange:

Error at adapter_init(): FMBTAndroidRunError: Unexpected exit status 255 from command "['timeout', '-k', '1', '60', 'adb', '-s', '*', 'shell', 'getprop', 'ro.build.version.release']".
    Output: 
    Error: error: device '*' not found
the * command is not supported;
 i'm using the latest fMTB version from the ubuntu repo

**Comment by shadeimi** [comment]
Building fMBT from the git repo i got:

15:43 $ fmbt regressiontest.conf 
<fmbt_log>
<version>
    0.30-1
</version>
<conf_load>
    <conf_file name="regressiontest.conf"/>
     <remote_pyaal_version>0.30-1</remote_pyaal_version>
    <remote msg="Error%20at%20adapter_init%28%29%3A%20AndroidConnectionError%3A%20Could%20not%20connect%20to%20device%28s%29%3A%20emulator-5554.%0ATraceback%20%28most%20recent%20call%20last%29%3A%0A%20%20File%20%22/tmp/remote_pyaal.Gf1Gs_.py%22%2C%20line%20405%2C%20in%20adapter_init%0A%20%20%20%20ret%20%3D%20x%28%29%0A%20%20File%20%22phone.aal%22%2C%20line%2048%2C%20in%20adapter_init1%0A%20%20%20%20d%20%3D%20fmbtandroid.Device%28%29%0A%20%20File%20%22/usr/local/lib64/python2.7/site-packages/fmbtandroid.py%22%2C%20line%20469%2C%20in%20__init__%0A%20%20%20%20%22%2C%20%22.join%28potentialDevices%29%29%29%0A"/>
Error at adapter_init(): AndroidConnectionError: Could not connect to device(s): emulator-5554.
Traceback (most recent call last):
  File "/tmp/remote_pyaal.Gf1Gs_.py", line 405, in adapter_init
    ret = x()
  File "phone.aal", line 48, in adapter_init1
    d = fmbtandroid.Device()
  File "/usr/local/lib64/python2.7/site-packages/fmbtandroid.py", line 469, in __init__
    ", ".join(potentialDevices)))

</conf_load>
fmbt: regressiontest.conf: 2 Initialising adapter failed: 

</fmbt_log>

**Comment by askervin** [comment]
I probably need to try with Fedora 23, but that'll take a little time. Everything looks good on latest Debian unstable and many Ubuntus.

**Comment by shadeimi** [comment]
ok i'll try with my ubuntu at home

**Comment by shadeimi** [comment]
i've the same behaviour with ubuntu, identical problem.

**Comment by askervin** [comment]
I was able to reproduce the first problem. It seems I was not using the latest adb after all, but the one installed in the system. The issue is now fixed with commit https://github.com/01org/fMBT/commit/9bb85130e927777674b55e39772d4cc0d9a732e8  fMBT's devel branch. Could you verify that this fixes your problem, please?

**Comment by shadeimi** [comment]
not selecting bitmaps automatically when recording
>>> 
exec: import fmbtandroid
time: 0.000 s
>>> 
exec: sut = fmbtandroid.Device()
exception: Could not connect to device(s): emulator-5554.
  Traceback (most recent call last):    
  File "/usr/local/bin/fmbt-scripter", line 1919, in _fmbtExec    
    exec statement in self._fmbtEnv    
  File "<string>", line 1, in <module>    
  File "/usr/local/lib64/python2.7/site-packages/fmbtandroid.py", line 470, in __init__    
    ", ".join(potentialDevices)))    
AndroidConnectionError: Could not connect to device(s): emulator-5554.
>>> 
time: 12.626 s
>>> 

But the device is recognized :)

**Comment by askervin** [comment]
I think I've found the problem. You should add SD Card to your emulator. 16 MB should be enough.

**Comment by askervin** [comment]
Error message that gives a hint on missing SD Card added to fmbtandroid.
https://github.com/01org/fMBT/commit/9a534c0b71865328ef02f1f5c98c0895c2eb99c5
Closing the bug. Please reopen if there are still issues with the connection.

**Comment by shadeimi** [comment]
great :) let me try, i'll let you know soon

**Comment by askervin** [comment]
Btw, just noticed that bitmaps and the Phone application UI have changed from 4.2.2 to 4.4.2. Please use 4.2.2 platform to see a successful phone test.

**Comment by shadeimi** [comment]
yes, my fault, but the swipe() funcion seems related to the screen size, i'll try ASAP
