### ISSUE TITLE
Error at adapter_init(): ValueError: Bitmap "lockscreen-lock.png" not readable in bitmapPath

### ISSUE THREAD

**Issue by shadeimi** [askervin/fmbt-androidtest#4]
✘-4 ~/git/fmbt-androidtest [master|✚ 6…15] 
14:47 $ git reset --hard
HEAD ora si trova a 8dfc1e0 README and comments added, swapping calls testable
✔ ~/git/fmbt-androidtest [master|…15] 
14:48 $ fmbt regressiontest.conf 
<fmbt_log>
<version>
    0.31-0.rc0-9bb8513
</version>
<conf_load>
    <conf_file name="regressiontest.conf"/>
     <remote_pyaal_version>0.31-0.rc0-9bb8513</remote_pyaal_version>
    <remote msg="Error%20at%20adapter_init%28%29%3A%20ValueError%3A%20Bitmap%20%22lockscreen-lock.png%22%20not%20readable%20in%20bitmapPath%20%0ATraceback%20%28most%20recent%20call%20last%29%3A%0A%20%20File%20%22/tmp/remote_pyaal.pMIFRg.py%22%2C%20line%20405%2C%20in%20adapter_init%0A%20%20%20%20ret%20%3D%20x%28%29%0A%20%20File%20%22phone.aal%22%2C%20line%2056%2C%20in%20adapter_init1%0A%20%20%20%20if%20d.verifyBitmap%28%22lockscreen-lock.png%22%29%3A%0A%20%20File%20%22/usr/local/lib64/python2.7/site-packages/fmbtgti.py%22%2C%20line%203374%2C%20in%20verifyBitmapWRAP%0A%20%20%20%20retval%20%3D%20loggerSelf.doCallLogException%28origMethod%2C%20args%2C%20kwargs%29%0A%20%20File%20%22/usr/local/lib64/python2.7/site-packages/fmbtgti.py%22%2C%20line%203366%2C%20in%20doCallLogException%0A%20%20%20%20try%3A%20return%20origMethod%28%2Aargs%2C%20%2A%2Akwargs%29%0A%20%20File%20%22/usr/local/lib64/python2.7/site-packages/fmbtgti.py%22%2C%20line%202383%2C%20in%20verifyBitmap%0A%20%20%20%20return%20self._lastScreenshot.findItemsByBitmap%28bitmap%2C%20%2A%2AoirArgs%29%20%21%3D%20%5B%5D%0A%20%20File%20%22/usr/local/lib64/python2.7/site-packages/fmbtgti.py%22%2C%20line%203436%2C%20in%20findItemsByBitmapWRAP%0A%20%20%20%20absPathBitmap%20%3D%20screenshotObj._paths.abspaths%28bitmap%29%5B0%5D%0A%20%20File%20%22/usr/local/lib64/python2.7/site-packages/fmbtgti.py%22%2C%20line%201335%2C%20in%20abspaths%0A%20%20%20%20raise%20ValueError%28%27Bitmap%20%22%25s%22%20not%20readable%20in%20bitmapPath%20%25s%27%20%25%20%28bitmap%2C%20%27%3A%27.join%28path%29%29%29%0A"/>
Error at adapter_init(): ValueError: Bitmap "lockscreen-lock.png" not readable in bitmapPath 
Traceback (most recent call last):
  File "/tmp/remote_pyaal.pMIFRg.py", line 405, in adapter_init
    ret = x()
  File "phone.aal", line 56, in adapter_init1
    if d.verifyBitmap("lockscreen-lock.png"):
  File "/usr/local/lib64/python2.7/site-packages/fmbtgti.py", line 3374, in verifyBitmapWRAP
    retval = loggerSelf.doCallLogException(origMethod, args, kwargs)
  File "/usr/local/lib64/python2.7/site-packages/fmbtgti.py", line 3366, in doCallLogException
    try: return origMethod(*args, **kwargs)
  File "/usr/local/lib64/python2.7/site-packages/fmbtgti.py", line 2383, in verifyBitmap
    return self._lastScreenshot.findItemsByBitmap(bitmap, **oirArgs) != []
  File "/usr/local/lib64/python2.7/site-packages/fmbtgti.py", line 3436, in findItemsByBitmapWRAP
    absPathBitmap = screenshotObj._paths.abspaths(bitmap)[0]
  File "/usr/local/lib64/python2.7/site-packages/fmbtgti.py", line 1335, in abspaths
    raise ValueError('Bitmap "%s" not readable in bitmapPath %s' % (bitmap, ':'.join(path)))

</conf_load>
fmbt: regressiontest.conf: 2 Initialising adapter failed: 

</fmbt_log>
✘-4 ~/git/fmbt-androidtest [master|…16]

**Comment by askervin** [comment]
Thanks for reporting! This code used deprecated way to set up path from which bitmaps are searched for. Fixed in commit 4e060b000c9939dcd8ec5d22ffdd765d98438f89.

**Comment by shadeimi** [comment]
14:56 $ fmbt regressiontest.conf 
<fmbt_log>
<version>
    0.31-0.rc0-9bb8513
</version>
<conf_load>
    <conf_file name="regressiontest.conf"/>
     <remote_pyaal_version>0.31-0.rc0-9bb8513</remote_pyaal_version>
    <remote error="I/O error: integer expected, got nothing."/>
Remote expected integer, got nothing
</conf_load>
fmbt: regressiontest.conf: 2 Initialising adapter failed: 

</fmbt_log>
✘-4 ~/git/fmbt-androidtest [master|…3] 
14:56 $ adb kill-server
✔ ~/git/fmbt-androidtest [master|…3] 
14:56 $ adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
✔ ~/git/fmbt-androidtest [master|…3] 
14:57 $ fmbt regressiontest.conf 
<fmbt_log>
<version>
    0.31-0.rc0-9bb8513
</version>
<conf_load>
    <conf_file name="regressiontest.conf"/>
     <remote_pyaal_version>0.31-0.rc0-9bb8513</remote_pyaal_version>
    <remote error="I/O error: integer expected, got nothing."/>
Remote expected integer, got nothing
</conf_load>
fmbt: regressiontest.conf: 2 Initialising adapter failed: 

</fmbt_log>
aal remote(remote_pyaal -l aal.log phone.aal) Terminated by a signal (11)

(process:22775): GLib-CRITICAL **: Source ID 1 was not found when attempting to remove it

**Comment by askervin** [comment]
That was exciting. Reading image dimensions worked fine on Debian, Ubuntu and Fedoras up to 22, but stopped working on 23. Anyway, this is fixed now in fMBT's devel branch by commit https://github.com/01org/fMBT/commit/46a6276ef1fd8b762c5f6b964bb1cff775000445. Thanks for your patience!  :)

**Comment by shadeimi** [comment]
✔ ~/git/fmbt-androidtest [master|…38] 
16:36 $ fmbt regressiontest.conf
<fmbt_log>
<version>
    0.31-0.rc0-46a6276
</version>
<conf_load>
    <conf_file name="regressiontest.conf"/>
     <remote_pyaal_version>0.31-0.rc0-46a6276</remote_pyaal_version>
</conf_load>
<conf_execute>
    <action_name name="i%3Alaunch%20phone"/>
    <action_name name="i%3Acall%20333"/>
    <action_name name="i%3Acall%20999"/>
    <action_name name="i%3Areturn%20to%20call%20in%20progress"/>
    <action_name name="i%3Aswap%20calls"/>
    <action_name name="i%3Areturn%20to%20homescreen"/>
    <action_name name="i%3Ahangup%20333"/>
    <action_name name="i%3Ahangup%20999"/>
    <tag_name name="homescreen"/>
    <tag_name name="phone"/>
    <test_engine>
        <tags enabled="homescreen"/>
        <remote msg="Assertion%20failure%20at%20adapter%28%29%20of%20tag%20%22homescreen%22%3A%20not%20in%20home%20screen%0ATraceback%20%28most%20recent%20call%20last%29%3A%0A%20%20File%20%22phone.aal%22%2C%20line%2080%2C%20in%20adapter%20of%20tag%20%22homescreen%22%0A%20%20%20%20assert%20d.waitBitmap%28%22home-dialer.png%22%29%2C%20%22not%20in%20home%20screen%22%0A"/>
Assertion failure at adapter() of tag "homescreen": not in home screen
Traceback (most recent call last):
  File "phone.aal", line 80, in adapter of tag "homescreen"
    assert d.waitBitmap("home-dialer.png"), "not in home screen"

        <status steps="0" coverage="0.000000" scov="0.000000e+00"/>
        <stop verdict="fail" reason="verifying%20tags%20%22homescreen%22%20failed."/>
        <current_time time="1456501017.585887"/>
        <elapsed_time time="8.113820"/>
    </test_engine>
</conf_execute>
fail: verifying tags "homescreen" failed.
</fmbt_log>

**Comment by shadeimi** [comment]
Seems that the emulated handset must have a proper resolution in order to use the swipe() method (the distance between the lock and the lock border should be calculated dinamically IMHO)

**Comment by askervin** [comment]
Swipe calculates the distance dynamically; swipeBitmap("lockscreen-lock.png", "e") starts from the middle of the recognized lock image and continues to the east until it hits the border of the screen. This should open the lock.

All methods that take coordinates as input accept resolution-independent values 0.0-1.0, and scale those to current resolution. In this example you can find call: swipe((.5,0.0),"s"), which means swiping from the middle (x) top (y) to the south. As distance is not given, it defaults to 1.0, meaning full length until it hits the border.

If you do not see the lock being swiped, it could be that the lock did not match the reference graphics. (4.4.2 and 4.2.2 locks are different, this example needs 4.2.2). If it is swiped but swiping does not open the lock, this is new issue.

**Comment by shadeimi** [comment]
Yes i've noticed this behaviour in the source code, but we've another issue :(
